void init_board_test();
void getter_board_test();
void print_row_test();
void print_blank_row_test();
void print_board_test0();
void print_board_test1();
void set_board_string_test();
void should_return_error_when_string_is_not_correct_length();
void set_poss_test();
